runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /youtube_servlet
  script: unused
  login: optional
  secure: optional
- url: /converter_servlet
  script: unused
  login: optional
  secure: optional
- url: /test_servlet
  script: unused
  login: optional
  secure: optional
- url: /youtube
  script: unused
  login: optional
  secure: optional
- url: /call_perspective
  script: unused
  login: optional
  secure: optional
- url: /keyword_search_servlet
  script: unused
  login: optional
  secure: optional
- url: /trending_servlet
  script: unused
  login: optional
  secure: optional
- url: /data
  script: unused
  login: optional
  secure: optional
- url: /username_servlet
  script: unused
  login: optional
  secure: optional
- url: /youtube_username_servlet
  script: unused
  login: optional
  secure: optional
- url: /searchh_servlet
  script: unused
  login: optional
  secure: optional
